// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oglvdtfixqlejpojykwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbHZkdGZpeHFsZWpwb2p5a3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTkxNTEsImV4cCI6MjA1NzY5NTE1MX0.5vmiupFPDMufOSDWmMA5sqXqPx_cSiBbR2kaVxUW1t4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);